//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyRung.Model
{
    using QuanLyRung.ViewModel;
    using System;
    using System.Collections.Generic;
    using System.Windows;

    public partial class Animal : BaseViewModel
    {
        private int _Id;
        public int Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }
        private string _DisplayName;
        public string DisplayName { get => _DisplayName; set { _DisplayName = value; OnPropertyChanged(); } }
        private int? _Count;
        public int? Count { get => _Count; set { _Count = value; OnPropertyChanged(); } }
        private int? _IdStorageAnimal;
        public int? IdStorageAnimal { get => _IdStorageAnimal; set { _IdStorageAnimal = value; OnPropertyChanged(); } }
        private string _StatusAnimal;
        public string StatusAnimal { get => _StatusAnimal; set { _StatusAnimal = value; OnPropertyChanged(); } }

        private DateTime? _DateInput;
        public DateTime? DateInput { get => _DateInput; set { _DateInput = value; OnPropertyChanged(); } }
        private StorageAnimal _StorageAnimal;
        public virtual StorageAnimal StorageAnimal { get => _StorageAnimal; set { _StorageAnimal = value; OnPropertyChanged(); } }
        
    }
}
