//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyRung.Model
{
    using QuanLyRung.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierWood : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierWood()
        {
            this.Wood = new HashSet<Wood>();
        }

        private int _Id;
        public int Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }
        private string _DisplayName;
        public string DisplayName { get => _DisplayName; set { _DisplayName = value; OnPropertyChanged(); } }
        private string _Adress;
        public string Adress { get => _Adress; set { _Adress = value; OnPropertyChanged(); } }
        private string _Typess;
        public string Typess { get => _Typess; set { _Typess = value; OnPropertyChanged(); } }
        private string _Form;
        public string Form { get => _Form; set { _Form = value; OnPropertyChanged(); } }
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wood> Wood { get; set; }
    }
}
