//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyRung.Model
{
    using QuanLyRung.ViewModel;
    using System;
    using System.Collections.Generic;
    using System.Windows.Controls;

    public partial class Wood : BaseViewModel
    {
        private int _Id;
        public int Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }
        private string _DisplayName;
        public string DisplayName { get => _DisplayName; set { _DisplayName = value; OnPropertyChanged(); } }
        private int? _Count;
        public int? Count { get => _Count; set { _Count = value; OnPropertyChanged(); } }
        private string _Unit;
        public string Unit { get => _Unit; set { _Unit = value; OnPropertyChanged(); } }
        private int? _IdSupplierWood;
        public int? IdSupplierWood { get => _IdSupplierWood; set { _IdSupplierWood = value; OnPropertyChanged(); } }
        private DateTime? _DateInput;
        public DateTime? DateInput { get => _DateInput; set { _DateInput = value; OnPropertyChanged(); } }

        private SupplierWood _SupplierWood;
        public virtual SupplierWood SupplierWood { get => _SupplierWood; set { _SupplierWood = value; OnPropertyChanged(); } }

       
    }
}
